services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: partner_locator
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
